src/lib/editor/elementManager.ts
src/lib/editor/eventHandler.ts
src/lib/editor/overlay/index.ts
src/lib/editor/overlay/rect.ts
src/routes/project/webview/WebviewArea.tsx

Correctly handle scroll

---

src/lib/editor/engine/styles/autolayout.ts
src/lib/editor/engine/styles/group.ts
src/lib/editor/engine/styles/index.ts
src/lib/editor/engine/styles/models.ts
src/lib/editor/engine/styles/numberUnit.ts
src/lib/editor/engine/styles/tag.ts
src/lib/editor/engine/styles/units.ts
src/routes/project/EditPanel/ManualTab.tsx
src/routes/project/EditPanel/inputs/NestedInput.tsx
src/routes/project/EditPanel/inputs/TagInfo.tsx
src/routes/project/EditPanel/inputs/TextInput.tsx

Refactor editor engine

---

.vscode/settings.json
common/constants.ts
common/helpers.ts
common/models.ts
electron/main/code/files.ts
electron/main/code/index.ts
electron/main/ipcEvents.ts
electron/main/tunnel/index.ts
src/lib/editor/engine/code/index.ts
src/routes/project/EditPanel/inputs/DisplayInput.tsx
src/routes/project/PublishModal/index.tsx
src/routes/project/SharePopver/index.tsx

Sharing with localtunnel and writing to code

---

.vscode/settings.json
README.md
docs/ROADMAP.md
electron/preload/webview/elements/index.ts
src/lib/editor/engine/code/index.ts
src/lib/editor/engine/index.ts
src/lib/editor/engine/webview/index.ts
src/routes/project/Canvas.tsx
src/routes/project/WebviewArea/Webview.tsx

Can now select web views when clicked on element to focus scroll and pan. Click outside to deselect.

Add webview selection state

---

electron/main/code/files.ts

Update open in vscode command

---

README.md
app/common/constants.ts
app/common/models.ts
app/electron/preload/webview/changes/index.ts
app/electron/preload/webview/elements/index.ts
app/electron/preload/webview/eventBridge.ts
app/src/components/ui/toggle-group.tsx
app/src/lib/editor/engine/index.ts
app/src/lib/editor/engine/styles/autolayout.ts
app/src/lib/editor/engine/styles/index.ts
app/src/lib/editor/engine/styles/numberUnit.ts
app/src/lib/editor/engine/styles/units.ts
app/src/lib/editor/eventHandler.ts
app/src/routes/project/EditPanel/ManualTab.tsx
app/src/routes/project/EditPanel/index.tsx
app/src/routes/project/EditPanel/inputs/AutoLayoutInput.tsx
app/src/routes/project/EditPanel/inputs/NestedInputs.tsx
app/src/routes/project/EditPanel/inputs/NumberUnitInput.tsx
app/src/routes/project/EditPanel/inputs/SelectInput.tsx
app/src/routes/project/WebviewArea/Webview.tsx

Fix update style bug

---

README.md

Update README with  demo video and wiki links

Add demo video and wiki links

---

README.md
app/common/constants.ts
app/src/lib/editor/engine/webviews/index.ts
app/src/routes/project/Canvas.tsx
app/src/routes/project/EditPanel/index.tsx
app/src/routes/project/SharePopover/index.tsx
app/src/routes/project/TopBar/index.tsx
app/src/routes/project/WebviewArea/Frame.tsx

Add empty state with docs and improve saving

---

app/common/constants.ts
app/package.json
app/src/components/Announcement/index.tsx

[Release] v0.0.4

---

app/src/routes/project/EditPanel/inputs/NumberUnitInput.tsx

[Bug] Fix number input arrow keys

---

app/package.json

Incremented version v0.0.5

---

app/electron/main/code/files.ts
app/electron/main/code/index.ts

Add prettier formatting, reading project's config

Run prettier formatting before writing code

---

app/package.json

Incremented version v0.0.6

---

app/package.json

Incremented version v0.0.7

---

app/common/helpers/index.ts
app/common/models/element/layers.ts
app/common/selector.ts
app/electron/preload/webview/api.ts
app/electron/preload/webview/elements/index.ts
app/src/lib/editor/engine/ast/index.ts
app/src/lib/editor/engine/code/index.ts
app/src/lib/editor/engine/dom/index.ts
app/src/lib/editor/engine/element/index.ts
app/src/lib/editor/eventHandler.ts
app/src/routes/project/LayersPanel/LayersTab.tsx
app/src/routes/project/LayersPanel/NodeIcon.tsx
app/src/routes/project/LayersPanel/TreeNode.tsx
app/src/routes/project/TopBar/ModeToggle.tsx
app/src/routes/project/TopBar/index.tsx
app/src/routes/project/WebviewArea/GestureScreen.tsx
app/src/routes/project/WebviewArea/index.tsx

Lazy load DOM tree processing to handle large pages

---

app/package.json

Incremented version v0.0.8

---

app/package.json
app/scripts/publish_tag.sh
cli/package.json

Incremented version v0.0.9

---

app/src/lib/editor/engine/ast/index.ts
app/src/routes/project/LayersPanel/LayersTab.tsx
app/src/routes/project/LayersPanel/Tree/TreeNode.tsx
demos/next/components/dashboard.tsx

Fix not being able to select element after writing to code

---

README.md

Update README.md for new video demo

---

README.md

Updated README.md Header Image

---

app/package.json

Publish version v0.0.10

---

app/package.json

Publish version v0.0.11

---

app/src/routes/project/LayersPanel/LayersTab.tsx
app/src/routes/project/LayersPanel/index.tsx

Resize layers panel

---

app/common/actions.ts
app/common/constants.ts
app/electron/main/code/babel.ts
app/electron/main/index.ts
app/electron/preload/webview/api.ts
app/electron/preload/webview/elements/insert.ts
app/electron/preload/webview/events.ts
app/src/lib/editor/engine/action/index.ts
app/src/lib/editor/engine/code/index.ts
app/src/lib/editor/engine/element/index.ts
app/src/lib/editor/engine/history/index.ts
app/src/lib/editor/eventHandler.ts
app/src/routes/project/EditPanel/ManualTab.tsx
app/src/routes/project/LayersPanel/Tree/TreeNode.tsx
app/src/routes/project/Toolbar/index.tsx
app/src/routes/project/TopBar/SharePopover/index.tsx
app/src/routes/project/WebviewArea/GestureScreen.tsx
app/src/routes/project/WebviewArea/index.tsx

Second part of insert: History for undo and redo. 
Still disabled until write to code is completed.

Insert with action and history

---

app/common/constants.ts
app/electron/preload/webview/elements/insert.ts
app/electron/preload/webview/events.ts
app/src/lib/editor/engine/ast/index.ts
app/src/lib/editor/engine/dom/index.ts
app/src/lib/editor/eventHandler.ts
app/src/routes/project/LayersPanel/Tree/TreeNode.tsx
app/src/routes/project/Toolbar/index.tsx
docs/src/app/page.tsx

Refresh layers after inserting and removing elements

---

app/common/actions.ts
app/common/constants.ts
app/common/helpers/index.ts
app/common/models/element/insert.ts
app/common/models/index.ts
app/electron/main/code/babel.ts
app/electron/main/code/index.ts
app/electron/main/events/code.ts
app/electron/preload/webview/api.ts
app/electron/preload/webview/elements/insert.ts
app/src/lib/editor/engine/code/index.ts
app/src/routes/project/Toolbar/index.tsx
app/src/routes/project/TopBar/PublishModal/index.tsx
docs/src/app/page.tsx

Working write to code for inserted components. Handles nested inserted components.
One edge case that still needs handling: Styling an element and inserting an element into it. This is not working currently because style and inserted code diffs are generated separately. Should generate both for each template node. 
Will do in a follow-up PR.

Write to code for insert

---

app/common/constants.ts
app/common/models/code.ts
app/common/models/element/insert.ts
app/common/models/index.ts
app/electron/main/code/babel.ts
app/electron/main/code/index.ts
app/electron/main/events/code.ts
app/electron/preload/webview/elements/insert.ts
app/src/lib/editor/engine/code/index.ts
app/src/lib/editor/engine/index.ts
app/src/routes/project/Toolbar/index.tsx
app/src/routes/project/TopBar/PublishModal/index.tsx
app/src/routes/project/WebviewArea/GestureScreen.tsx
app/src/routes/project/WebviewArea/Overlay.tsx

Handle insert edge cases

---

app/package.json

Publish version v0.0.12

---

app/electron/main/code/ast.ts
app/electron/main/events/code.ts
app/src/lib/editor/engine/ast/index.ts

Better matching instance finding

---

app/electron/main/code/babel.ts
app/src/lib/editor/engine/code/index.ts

Fix writing inside instance element

---

app/common/models/element/layers.ts
app/src/lib/editor/engine/ast/index.ts

Make layers insert in the right order

---

.github/workflows/build.yml

This PR updates the `build` Github workflow file to build Onlook for Windows when a new release is built

Build Windows app as part of releases

---

app/package.json

Publish version v0.0.14

---

README.md
SECURITY.md
app/common/constants.ts
app/package.json
app/src/routes/project/TopBar/index.tsx
app/src/routes/project/WebviewArea/BrowserControl.tsx
app/src/routes/project/WebviewArea/Frame.tsx
demos/babel/src/ReadDocs.jsx
package.json

Detect when Onlook plugin is enabled in page

---

app/src/routes/project/Canvas/HotkeysArea.tsx
app/src/routes/project/Canvas/index.tsx

Refactor hotkeys

---

app/src/lib/editor/engine/drag/index.ts
app/src/lib/editor/engine/index.ts
app/src/lib/editor/engine/insert/index.ts
app/src/routes/project/WebviewArea/Frame.tsx
app/src/routes/project/WebviewArea/GestureScreen.tsx

Split insert functionality into editor engine sub-class and create drag to order stubs

Setup drag to reorder - Refactor gesture screen

---

app/common/hotkeys.ts
app/electron/main/code/babel.ts
app/src/routes/project/Canvas/HotkeysArea.tsx

Escape to design

---

app/common/hotkeys.ts
app/src/routes/project/Canvas/HotkeysArea.tsx
app/src/routes/project/Toolbar/index.tsx
app/src/routes/project/TopBar/ModeToggle.tsx

* Fix tooltips with togglegroupitem
* Hotkeys fix for Windows using mod instead of meta

Various bug fixes - Pt.2

---

app/src/routes/project/index.tsx

Disable text select

---

app/package.json

Publish version v0.0.16

---

app/common/helpers/template.ts
app/common/models/code.ts
app/common/models/element/domAction.ts
app/electron/main/code/diff/index.ts
app/electron/main/code/templateNode.ts
app/electron/preload/webview/elements/insert.ts
app/electron/preload/webview/elements/move/index.ts
app/electron/preload/webview/events.ts
app/src/lib/editor/engine/code/index.ts

Drag to reorder write-to-code infrastructure

---

app/package.json

Publish version v0.0.17

---

app/src/lib/editor/engine/overlay/index.ts
app/src/lib/editor/engine/overlay/rect.ts

This pull request addresses the alignment issue(#97) of the text within the red background rectangle in the SVG rendering. The adjustments ensure that the text is correctly centered both horizontally and vertically within the rectangle.

feat: dimension label next to selection

---

.github/workflows/build.yml

- upgrade actions
- homogeneous YAML lists
- use GHA working directory
- use the new `github.token`

Improve build workflow a bit

---

app/package.json

Publish version v0.0.19

---

app/electron/preload/webview/elements/move/drag.ts
app/src/lib/editor/engine/index.ts
app/src/routes/project/RightClickMenu/index.tsx

Preserve computed size when dragging + Add devtool

---

app/electron/preload/webview/elements/insert.ts
app/electron/preload/webview/events.ts
app/src/lib/editor/eventHandler.ts
app/src/routes/project/TopBar/OpenCode/index.tsx

Update layers when elements inserted/removed

---

app/common/constants.ts
app/src/routes/project/Canvas/HotkeysArea.tsx
app/src/routes/project/LayersPanel/Tree/TreeNode.tsx

- Update tooltip trigger position on layer
- Disable cmd+option hotkey for toggling modes

Miscellaneous bug fixes

---

app/package.json

Publish version v0.0.20

---

app/common/constants.ts
app/common/models/element/index.ts
app/common/models/settings.ts
app/electron/main/analytics/index.ts
app/electron/main/code/index.ts
app/electron/main/events/settings.ts
app/electron/main/storage/index.ts
app/src/lib/editor/engine/canvas/index.ts
app/src/lib/editor/engine/index.ts
app/src/lib/editor/engine/insert/index.ts
app/src/lib/editor/engine/move/index.ts
app/src/lib/editor/messageBridge.ts
app/src/routes/project/Canvas/HotkeysArea.tsx
app/src/routes/project/Canvas/index.tsx
app/src/routes/project/WebviewArea/Frame.tsx
app/src/routes/project/WebviewArea/GestureScreen.tsx
app/src/routes/project/WebviewArea/ResizeHandles.tsx
app/src/routes/project/WebviewArea/index.tsx

Persist project settings

---

app/common/constants.ts
app/common/helpers/index.ts
app/common/selector.ts
app/electron/preload/webview/bundles/csstree.esm.js
app/electron/preload/webview/bundles/index.ts
app/electron/preload/webview/bundles/uuid.js
app/electron/preload/webview/changes/index.ts
app/electron/preload/webview/dom.ts
app/electron/preload/webview/elements/helpers.ts
app/electron/preload/webview/elements/move/drag.ts
app/electron/preload/webview/events.ts
app/electron/preload/webview/index.ts
app/eslint.config.js
app/src/lib/editor/engine/style/index.ts
app/src/lib/editor/eventHandler.ts
app/src/routes/project/WebviewArea/Frame.tsx
demos/next/components/dashboard.tsx

Process dom with uuid on load

---

app/package.json

Publish version v0.0.21

---

.github/workflows/build.yml
app/package.json

Publish version v0.0.22

---

app/package.json

Publish version v0.0.23

---

app/common/constants.ts
app/common/models/code.ts
app/common/models/element/domAction.ts
app/electron/main/code/diff/index.ts
app/electron/main/code/diff/transform.ts
app/electron/preload/webview/api.ts
app/electron/preload/webview/elements/text.ts
app/electron/preload/webview/events/index.ts
app/src/lib/editor/engine/code/index.ts
app/src/lib/editor/engine/overlay/textEdit.ts
app/src/lib/editor/engine/text/index.ts
app/src/routes/project/TopBar/PublishModal/index.tsx
demos/next/components/dashboard.tsx

Text edit - Write to code

---

app/electron/main/code/diff/index.ts

This ends up just creating unnecessary lines on diff

Revert retaining lines on write

---

app/common/actions.ts
app/common/models/element/domAction.ts
app/electron/main/code/diff/transform.ts
app/electron/preload/webview/elements/insert.ts
app/electron/preload/webview/events/index.ts
app/electron/preload/webview/events/publish.ts
app/src/lib/editor/engine/action/index.ts
app/src/lib/editor/engine/insert/index.ts
app/src/lib/editor/eventHandler.ts
app/src/routes/project/Canvas/HotkeysArea.tsx
app/src/routes/project/Toolbar/index.tsx
app/src/routes/project/WebviewArea/GestureScreen.tsx

Allow inserting text

---

docs/src/app/quickstart/page.tsx

Docs update

---

app/src/routes/project/WebviewArea/index.tsx

Reload WebviewArea on canvas change

---

app/electron/main/code/diff/transform.ts
app/src/routes/project/Canvas/HotkeysArea.tsx

Allow clear text

---

cli/package.json
cli/src/create/index.ts
cli/src/setup/constants.ts
cli/src/setup/utils.ts
cli/tsconfig.json

Add Yarn, Pnpm, Bun package handlers

Add CLI package manager detection 

---

app/common/hotkeys.ts
app/electron/preload/webview/api.ts
app/electron/preload/webview/elements/helpers.ts
app/electron/preload/webview/elements/insert.ts
app/electron/preload/webview/elements/remove.ts
app/src/lib/editor/engine/action/index.ts
app/src/lib/editor/engine/index.ts
app/src/lib/editor/engine/overlay/textEdit.ts
app/src/routes/project/Canvas/HotkeysArea.tsx

Backspace to delete elements

---

app/src/App.tsx
app/src/lib/routes/index.ts
app/src/routes/Provider.tsx
app/src/routes/index.tsx
app/src/routes/login/index.tsx

Add app routing

---

app/src/lib/editor/engine/canvas/index.ts
app/src/routes/projects/ProjectsTab/Create/New/SelectFolder.tsx
app/src/routes/projects/ProjectsTab/Select/Carousel.tsx

Create flow misc changes

---

app/src/components/ui/button.tsx
app/src/components/ui/dropdown-menu.tsx
app/src/components/ui/input.tsx
app/src/components/ui/label.tsx
app/src/routes/editor/EditPanel/index.tsx
app/src/routes/editor/LayersPanel/index.tsx
app/src/routes/editor/Toolbar/index.tsx
app/src/routes/editor/TopBar/ModeToggle/index.tsx
app/src/routes/editor/TopBar/OpenCode/index.tsx
app/src/routes/editor/TopBar/ProjectSelect/index.tsx
app/src/routes/editor/TopBar/index.tsx
app/src/routes/editor/WebviewArea/BrowserControl.tsx
app/src/routes/projects/ProjectsTab/Create/Load/SelectFolder.tsx
app/src/routes/projects/ProjectsTab/Create/Load/Verify.tsx
app/src/routes/projects/ProjectsTab/Create/Name.tsx
app/src/routes/projects/ProjectsTab/Create/New/Run.tsx
app/src/routes/projects/ProjectsTab/Create/New/SelectFolder.tsx
app/src/routes/projects/ProjectsTab/Create/New/Setup.tsx
app/src/routes/projects/ProjectsTab/Select/Carousel.tsx
app/src/routes/projects/ProjectsTab/Select/Info.tsx
app/src/routes/projects/ProjectsTab/Select/ProjectSettingsButton.tsx
app/src/routes/projects/ProjectsTab/Select/index.tsx
app/src/routes/projects/SettingsTab/index.tsx
app/src/routes/projects/TopBar/ModeToggle/index.tsx
app/tailwind.config.mjs

Tons of small style changes and improvements to the Editor and Project UI as well as baseline components to be more compliant with our design system.

Improved styling and increase click-area for label buttons

---

app/electron/main/index.ts
app/electron/preload/browserview/index.ts
app/src/lib/auth/index.ts
app/src/routes/index.tsx
app/src/routes/projects/ProjectsTab/Select/Carousel.tsx
app/src/routes/projects/TopBar/index.tsx
app/src/routes/signin/index.tsx

Auth integration

---

app/common/constants.ts
app/electron/main/events/analytics.ts
app/package.json
app/src/components/Announcement/index.tsx
app/src/routes/projects/SettingsTab/index.tsx

Publish version v0.0.26

---

app/package.json

Publish version v0.0.27

---

app/electron-builder.json5
app/package.json

Publish version v0.0.28

---

app/electron/main/code/diff/index.ts
app/electron/main/code/diff/transform.ts
app/electron/preload/webview/elements/helpers.ts
app/electron/preload/webview/elements/insert.ts
app/src/routes/editor/EditPanel/inputs/NestedInputs.tsx
demos/remix/app/routes/_index.tsx

Improve write to code

---

app/src/lib/editor/engine/insert/index.ts

Better insert

---

app/package.json

Publish version v0.0.29

---

app/common/constants.ts
app/electron/preload/webview/elements/move/drag.ts
demos/remix/app/routes/_index.tsx

Fix drag position

---

app/package.json

Publish version v0.0.30

---

app/electron/preload/webview/api.ts
app/electron/preload/webview/elements/move/index.ts
app/src/lib/editor/engine/index.ts
app/src/lib/editor/engine/move/index.ts
app/src/routes/editor/LayersPanel/LayersTab.tsx
app/src/routes/editor/LayersPanel/Tree/TreeNode.tsx

Dragging layers to reorder

---

app/common/ide.ts
app/electron/main/code/index.ts

Zed API not handling lines atm. Disabling until fixed.
https://github.com/zed-industries/zed/issues/14820

Disable line and column for Zed

---

app/package.json

Publish version v0.0.31

---

app/package.json

Publish version v0.0.32

---

app/src/lib/editor/engine/code/index.ts
app/src/routes/editor/TopBar/index.tsx

Instant write-to-code support

---

app/electron/main/index.ts

Handle windows url callback

---

app/electron/main/analytics/index.ts

Add platform to user identity

---

app/package.json

Publish version v0.0.34

---

app/src/routes/projects/ProjectsTab/Create/Load/Verify.tsx
app/src/routes/projects/ProjectsTab/Create/index.tsx

Handles edge cases a bit better.

Allow skipping verification for new project

---

app/package.json

Publish version v0.0.35

---

app/src/routes/editor/Canvas/index.tsx

Clamp x and y position

---

app/electron/main/storage/images.ts
app/electron/preload/webview/api.ts
app/electron/preload/webview/elements/style.ts
app/src/lib/editor/engine/index.ts
app/src/lib/editor/engine/overlay/prosemirror/index.ts
app/src/lib/editor/engine/overlay/textEdit.ts
app/src/lib/editor/engine/text/index.ts
app/src/routes/projects/ProjectsTab/Select/Carousel.tsx

1. Enter to stop editing
2. Correct editing text color
3. No prevent default on scroll carousel

Text edit improvements

---

app/package.json

Publish version v0.0.36

---

app/electron/main/analytics/index.ts

Add app version to analytics

---

.github/workflows/build.yml
app/electron/main/analytics/index.ts

Fix electron build issue

---

app/electron-builder.json5
app/package.json

Publish version v0.0.37

---

app/electron/preload/browserview/index.ts
app/src/lib/utils.ts
app/src/routes/projects/ProjectsTab/Create/New/SelectFolder.tsx
app/src/routes/projects/helpers.ts

Use correct slashes for Windows

---

.github/workflows/build.yml
app/eslint.config.js
app/package.json

This fixes the build issue in main

Remove eslint compat

---

app/common/hotkeys.ts
app/src/routes/editor/Canvas/HotkeysArea.tsx
demos/next/components/dashboard.tsx

Add support for additional delete hotkey

chore: Add support for additional delete hotkey

---

app/src/lib/editor/engine/action/index.ts
app/src/lib/editor/engine/code/index.ts
app/src/lib/editor/engine/dom/index.ts
app/src/lib/editor/engine/element/index.ts
app/src/lib/editor/engine/index.ts
app/src/lib/editor/engine/insert/index.ts
app/src/lib/editor/engine/move/index.ts
app/src/lib/editor/engine/style/index.ts
app/src/lib/editor/engine/text/index.ts

Refactor editor engine submodules

---

app/package.json

Publish version v0.0.39

---

app/electron/preload/webview/elements/dom/copy.ts
app/src/lib/editor/engine/copy/index.ts

Clean cloned node

---

app/common/models/index.ts
app/electron/main/code/diff/helpers.ts
app/electron/main/code/diff/insert.ts
app/electron/main/code/diff/move.ts
app/electron/main/code/diff/remove.ts
app/electron/main/code/moveKeys.ts
app/electron/main/events/code.ts
app/electron/preload/webview/api.ts
app/electron/preload/webview/elements/dom/copy.ts
app/electron/preload/webview/elements/dom/helpers.ts
app/electron/preload/webview/elements/dom/insert.ts
app/src/lib/editor/engine/code/index.ts
app/src/lib/editor/engine/copy/index.ts
app/src/lib/editor/engine/element/index.ts

Copy paste improvements

---

app/package.json

Publish version v0.0.40

---

app/src/App.tsx

Temporary dark mode by default per https://github.com/onlook-dev/onlook/issues/510

Default to dark theme for now

---

app/src/routes/projects/ProjectsTab/Select/ProjectSettingsButton.tsx

Ability to rename project via ProjectSettingsButton
Ability to rename project via ProjectSettingsButton
- [X ] New feature

Ability to rename project

---

app/electron/main/code/diff/helpers.ts

Decrease template node match fuzziness

---

app/package.json

Publish version v0.0.41

---

app/common/constants.ts
app/electron/main/code/cleanKeys.ts
app/electron/main/code/diff/helpers.ts
app/electron/main/code/diff/insert.ts
app/electron/main/events/code.ts
app/electron/preload/webview/elements/dom/insert.ts
app/electron/preload/webview/events/dom.ts
app/electron/preload/webview/events/index.ts
app/src/lib/editor/engine/action/index.ts
app/src/lib/editor/engine/code/index.ts
app/src/routes/editor/TopBar/OpenCode/index.tsx

Insert + remove reliability

---

cli/package.json
plugins/babel/package.json
plugins/next/package.json
utils/package.json

Add onlook repo to npm packages

---

app/package.json

Publish version v0.0.42

---

app/common/models/index.ts
app/src/lib/editor/engine/index.ts
app/src/lib/editor/engine/insert/index.ts
app/src/lib/editor/engine/text/index.ts
app/src/lib/editor/styles/numberUnit.ts
app/src/lib/models.ts
app/src/routes/editor/Canvas/Hotkeys/index.tsx
app/src/routes/editor/EditPanel/inputs/single/ColorInput/index.tsx
app/src/routes/editor/EditPanel/inputs/single/SelectInput.tsx
app/src/routes/editor/EditPanel/inputs/single/TextInput.tsx
app/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
app/src/routes/editor/WebviewArea/GestureScreen.tsx

- Update stack to say flex
- Default to px as a unit on text inputs
- Update text mode to edit on click

Small editor bugs

---

app/src/components/Announcement/index.tsx
app/src/components/ui/logo.tsx
app/src/lib/editor/engine/code/index.ts
app/src/routes/editor/EditPanel/inputs/compound/BorderInput.tsx

Handle border edits

---

app/src/routes/projects/ProjectsTab/Select/Carousel.tsx
app/src/routes/projects/ProjectsTab/Select/EditAppButton.tsx
app/src/routes/projects/ProjectsTab/Select/Info.tsx

Handle carousel light mode

---

app/src/routes/projects/ProjectsTab/Select/ProjectSettingsButton.tsx

Add validation for rename project input
Add validation for rename project input

Add validation for rename input

---

app/src/components/ui/alert-dialog.tsx
app/src/routes/editor/Canvas/Hotkeys/Delete.tsx

fixes the card background color issue from the root

fixes #554: fix delete card in light mode

---

app/package.json
app/src/routes/projects/ProjectsTab/Create/New/Run.tsx

Publish version v0.0.44

---

app/electron/main/code/diff/transform.ts
app/src/lib/editor/engine/code/index.ts

Improve write code timing

---

app/package.json

Publish version v0.0.45

---

app/src/routes/editor/RightClickMenu/index.tsx

Ungrouping is swapped

---

app/package.json

Publish version v0.0.46

---

app/src/routes/editor/WebviewArea/BrowserControl.tsx
app/src/routes/editor/WebviewArea/Frame.tsx
app/src/routes/projects/ProjectsTab/Create/New/Run.tsx

Implemented a preset dimension button as mentionned in #487 
With this PR we'll add a button that allows user to change the dimension of the screen they are working on , to see how their works will be displayed in different screens

Feature - Window dimension presets (#487)

---

app/src/lib/editor/engine/code/index.ts
app/src/lib/editor/engine/element/index.ts
app/src/routes/editor/EditPanel/inputs/single/TailwindInput.tsx

Slight improvement on tailwind write

---

app/src/routes/editor/TopBar/ProjectSelect/ProjectNameInput.tsx
app/src/routes/editor/TopBar/ProjectSelect/index.tsx

Fixes #551 
This PR adds inline editing functionality and keyboard shortcuts for a more intuitive user experience.
NEW FEATURE - inline project renaming capability (allow project name edit directly from the main interface)
https://github.com/user-attachments/assets/7de668a4-d6e5-4957-bbdd-a5ef0ae1596c

#551  - Added project name changing functionality on main interface with inline editing and keyboard shortcuts.

---

app/src/routes/editor/WebviewArea/BrowserControl.tsx

fixes #580
**Changes**: 
- Adds check for forward button to show only if going forward is possible.
- Adds animation when forward button comes into view.

feat: Animate forward button into view if going forward is possible

---

app/src/routes/editor/WebviewArea/BrowserControl.tsx

Catch can go back and forward calls

---

app/common/models/project.ts
app/electron/main/events/index.ts
app/src/components/AppBar/WindowsControls.tsx

Modified the color of the close button to red on hover and active states, the shape of the buttons to fill the div, also the icon for maximize button. I also added in the unmaximize functionality to the maximize button, which was missing before. 
https://github.com/user-attachments/assets/0fc344ed-538f-472d-bd2c-b220b20a6ddb
https://github.com/user-attachments/assets/d02409f8-61f7-46be-9c46-c1b3d88e84cb
https://github.com/user-attachments/assets/b8e988e4-51b9-44fd-be12-23b8c4719c01

Fix maximize on windows and modify styles

---

app/package.json

Publish version v0.0.47

---

app/src/routes/editor/WebviewArea/Frame.tsx

Show dom failed screen after 3s delay

---

app/src/lib/editor/engine/element/index.ts
app/src/lib/editor/engine/overlay/index.ts
app/src/lib/editor/engine/overlay/measurement.ts
app/src/routes/editor/Canvas/Hotkeys/index.tsx
app/src/routes/editor/WebviewArea/GestureScreen.tsx

Link to issue: https://github.com/onlook-dev/onlook/issues/540
Implement Measurement overlay to show the distance between 2 rectangles when holding Alt/Option down.
Demo:
https://github.com/user-attachments/assets/a7ff6477-a305-4856-8465-a6c5992708be

[feat] Hold down alt/option to measure

---

app/common/color.ts
app/src/routes/editor/Canvas/Hotkeys/index.tsx

Update palette to use hex6

---

app/common/color.ts
app/src/routes/editor/EditPanel/ManualTab/single/ColorInput/PopoverColorPicker.tsx

Update color picker palette when color changes

---

app/src/routes/projects/ProjectsTab/Select/Carousel.tsx

Remove stray console log

---

app/src/routes/editor/LayersPanel/Tree/TreeNode.tsx

Make layers update based on canvas selection

---

app/common/color.ts
app/src/routes/editor/EditPanel/StylesTab/compound/BorderInput.tsx
app/src/routes/editor/EditPanel/StylesTab/single/ColorInput/PopoverColorPicker.tsx
app/src/routes/editor/EditPanel/StylesTab/single/ColorInput/index.tsx

Add a non color button

---

app/src/routes/projects/ProjectsTab/Select/Carousel.tsx

Fix no preview bug

---

app/src/routes/projects/ProjectsTab/Select/Carousel.tsx

Prevent multiple scroll on carousel

---

app/electron/preload/webview/elements/move/drag.ts
app/src/routes/editor/WebviewArea/Frame.tsx
app/src/routes/projects/ProjectsTab/Select/Carousel.tsx

Handle webview scroll position on drag 

---

app/package.json

Publish version v0.0.48

---

app/electron-builder.json5
app/package.json
app/src/index.css

Publish version v0.0.49

---

app/src/lib/projects/index.ts

Fix returning empty project for testing

---

apps/studio/src/routes/editor/Toolbar/index.tsx

Import by type got messed up by my refactor.

Fix type import

---

apps/studio/src/routes/editor/WebviewArea/Frame.tsx

Fix show dom failed not changing

---

apps/studio/src/lib/editor/engine/ast/index.ts
apps/studio/src/lib/editor/engine/ast/map.ts
apps/studio/src/lib/editor/engine/dom/index.ts
apps/studio/src/lib/editor/eventHandler.ts
apps/studio/src/routes/editor/EditPanel/StylesTab/single/TailwindInput.tsx
apps/studio/src/routes/editor/LayersPanel/LayersTab.tsx
apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
apps/studio/src/routes/editor/WebviewArea/BrowserControl.tsx

Support multiple windows in layers

---

apps/studio/src/routes/editor/EditPanel/StylesTab/single/TailwindInput.tsx

Improve tailwind input

---

apps/studio/src/routes/editor/EditPanel/StylesTab/single/TailwindInput.tsx

Improve tailwind input pt.2

---

apps/studio/src/routes/editor/Canvas/index.tsx

Increase bounds

---

apps/studio/src/lib/editor/engine/insert/index.ts

More explicit insert text

---

apps/studio/src/routes/projects/SettingsTab/index.tsx
apps/studio/src/routes/projects/TopBar/index.tsx

Enable settings page in dev mode

---

.github/workflows/build.yml
apps/studio/package.json
apps/studio/src/routes/editor/EditPanel/index.tsx

Publish version v0.0.54

---

apps/studio/package.json
apps/studio/src/components/AppBar/WindowsControls.tsx

Publish version v0.0.55

---

apps/studio/electron/preload/webview/elements/style.ts
apps/studio/src/lib/editor/engine/chat/prompt.ts
apps/studio/src/lib/editor/styles/autolayout.ts
apps/studio/src/routes/editor/EditPanel/StylesTab/single/AutoLayoutInput.tsx
apps/studio/src/routes/editor/EditPanel/StylesTab/single/TailwindInput/AutoComplete.tsx
apps/studio/src/routes/editor/EditPanel/StylesTab/single/TailwindInput/index.tsx

* Better autolayout unit parsing
* Default autolayout to auto + hug
* Apply tailwind input on auto-complete
* Add custom history for tailwind input
* Update AI prompt formatting

Various editor bugs pt.2

---

apps/studio/src/routes/projects/ProjectsTab/Create/ChooseMethod.tsx
apps/studio/src/routes/projects/ProjectsTab/index.tsx
packages/ui/tailwind.config.ts

Restore missing new project color tokens

---

apps/studio/package.json
apps/studio/src/routes/editor/EditPanel/StylesTab/single/TailwindInput/index.tsx

Publish version v0.0.57

---

apps/studio/src/routes/editor/TopBar/OpenCode/index.tsx
apps/studio/src/routes/editor/WebviewArea/BrowserControl.tsx

Implement subtle animation according to https://github.com/onlook-dev/onlook/issues/568
https://github.com/user-attachments/assets/5f13069c-7f25-4661-a2da-cd92f4975bb5

Feat/subtle animation #568

---

apps/studio/src/routes/editor/TopBar/OpenCode/index.tsx

Implement text transition according to https://github.com/onlook-dev/onlook/issues/210
https://github.com/user-attachments/assets/6bfbacdf-d769-4a87-ae1f-54b128558858

feat: implement text transition for IDE dropdown #210

---

apps/studio/common/hotkeys.ts
apps/studio/src/components/ui/hotkeys-label.tsx
apps/studio/src/routes/editor/Canvas/Hotkeys/index.tsx
apps/studio/src/routes/editor/Canvas/index.tsx
apps/studio/src/routes/editor/TopBar/ZoomControls/index.tsx
apps/studio/src/routes/editor/TopBar/index.tsx
apps/studio/src/routes/editor/index.tsx

Zoom Controls added - UI, logic 
[#475](https://github.com/onlook-dev/onlook/issues/475)

[feat] Infinite Canvas Zoom controls 

---

apps/studio/package.json

Publish version v0.0.59

---

apps/studio/src/lib/editor/styles/numberUnit.ts

Fix double style change from entering and blurring

---

apps/studio/src/routes/editor/Toolbar/Terminal/RunButton.tsx
apps/studio/src/routes/editor/Toolbar/index.tsx
apps/studio/src/routes/editor/WebviewArea/Frame.tsx

- Added in character transition for smoother text when we have more messages to show.
- Added in light and dark mode radial gradient 
- Improved copy of the empty state

Terminal Toolbar Style Improvements

---

apps/studio/electron/main/code/diff/helpers.ts
apps/studio/electron/main/code/files.ts
apps/studio/electron/main/code/helpers.ts
apps/studio/electron/main/run/cleanup.ts
apps/studio/electron/main/run/index.ts
apps/studio/electron/preload/webview/elements/text.ts
apps/studio/src/routes/editor/Toolbar/Terminal/RunButton.tsx
apps/studio/src/routes/editor/TopBar/ProjectSelect/index.tsx
apps/studio/src/routes/projects/ProjectSettingsModal.tsx
apps/studio/src/routes/projects/ProjectsTab/Select/ProjectSettingsButton.tsx

Launch fixes for v0.1

---

apps/studio/package.json

Publish version v0.1.0

---

apps/studio/src/lib/projects/index.ts
apps/studio/src/routes/projects/ProjectsTab/Create/Load/SetUrl.tsx
apps/studio/src/routes/projects/ProjectsTab/Create/index.tsx

Write run command on create

---

apps/studio/package.json

Publish version v0.1.2

---

apps/studio/package.json

Publish version v0.1.3

---

apps/studio/common/hotkeys.ts
apps/studio/src/lib/editor/engine/index.ts
apps/studio/src/lib/models.ts
apps/studio/src/routes/editor/EditPanel/index.tsx
apps/studio/src/routes/editor/RightClickMenu/index.tsx

Right click elements, hotkeys and changing tab
- [ x] New feature

#723: Right-click to add to AI chat + Hotkey for adding to chat

---

apps/studio/package.json

Publish version v0.1.4

---

apps/studio/electron/main/requirements/index.ts

This should cover any environment like nvm or fnm. As long as npm command works.

Check npm instead of node

---

apps/studio/electron/main/requirements/index.ts

Check for more paths for node version managers

Check for version managers

---

apps/studio/src/lib/editor/engine/chat/message/assistant.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatControls/index.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatInput.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/MarkdownRenderer.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/UserMessage.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/index.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/CodeChangeDisplay/index.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ContextPills/DraftContextPill.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ContextPills/SentContextPill.tsx
packages/models/src/chat/message/message.ts

Tons of UI polish on the chat messages
- Code message rounded / styling to be a bit tighter + border
- Copy / Edit improvements for easier-to-click buttons + hover state + edit the message functionality + ESC and ENTER hotkeys for cancel / submit
- Delete icon for drafting message pills
- Wrapped the pill div so the user can see all of the objects they have selected without having to side-scroll. 
- Improved styling of all element pills
- Improved hover state of the chat functional buttons up-top.

Tons of AI Chat UI improvements

---

apps/studio/package.json
packages/foundation/README.md

Publish version v0.1.6

---

apps/studio/electron/main/code/index.ts

directory picker allows creating new directories in macOS

feat: directory picker allows creating new directories in macOS

---

apps/studio/src/routes/editor/WebviewArea/BrowserControl/index.tsx

Make browsercontrols observe mode

---

apps/studio/electron/main/run/helpers.ts
apps/studio/electron/main/run/setup.ts
apps/studio/electron/preload/webview/api.ts
apps/studio/electron/preload/webview/elements/dom/helpers.ts
apps/studio/src/lib/editor/engine/ast/index.ts
apps/studio/src/lib/editor/engine/element/index.ts
packages/models/src/constants/index.ts
packages/models/src/element/layers.ts
packages/models/src/element/templateNode.ts

Introduced core element types for body tags and elements with return statement parent
Also added a warning message when attempting to delete a core element. 
Related: #851

Fixed deleting core elements

---

apps/studio/src/routes/editor/EditPanel/StylesTab/single/TailwindInput/AutoComplete.tsx

1. No default tailwind autocomplete selection
2. Improve up and down keys

Tailwind autocomplete improvements

---

apps/studio/src/lib/editor/engine/element/index.ts
apps/studio/src/lib/editor/engine/overlay/utils.ts
apps/studio/src/routes/editor/Canvas/Overlay/ClickRect.tsx
apps/studio/src/routes/editor/Canvas/Overlay/ResizeHandles.tsx
apps/studio/src/routes/editor/WebviewArea/Frame.tsx
apps/studio/src/routes/projects/ProjectsTab/Select/EditAppButton.tsx

Resize handles in overlay

---

apps/studio/src/lib/editor/engine/insert/index.ts
apps/studio/src/lib/editor/engine/overlay/index.ts
apps/studio/src/lib/editor/engine/overlay/state.ts
apps/studio/src/lib/editor/engine/overlay/utils.ts
apps/studio/src/lib/editor/engine/text/index.ts
apps/studio/src/routes/editor/Canvas/Overlay/BaseRect.tsx
apps/studio/src/routes/editor/Canvas/Overlay/InsertRect.tsx
apps/studio/src/routes/editor/Canvas/Overlay/index.tsx
apps/studio/src/routes/editor/Canvas/index.tsx
apps/studio/src/routes/editor/TopBar/ZoomControls/index.tsx
apps/studio/src/routes/editor/WebviewArea/GestureScreen.tsx
packages/models/src/constants/index.ts

Insert rect fix

---

apps/studio/src/lib/editor/engine/overlay/prosemirror/index.ts

Add background color to editor

---

apps/studio/src/routes/editor/EditPanel/StylesTab/compound/NestedInputs.tsx

Fix nested margin padding

---

apps/studio/src/lib/editor/engine/overlay/utils.ts
packages/foundation/README.md

Fix canvas throw error

---

apps/studio/src/routes/editor/RightClickMenu/index.tsx

Disable instead of hide view element code if no root

---

apps/studio/src/routes/editor/Canvas/Overlay/ResizeHandles.tsx
apps/studio/src/routes/editor/EditPanel/WindowSettings/FrameDimensions.tsx

Double-click to resize element

---

apps/studio/src/routes/editor/Canvas/Overlay/ResizeHandles.tsx

Restore drag and swap doubleclick

---

apps/studio/electron/main/code/classes.ts

Empty input if no classname

---

apps/studio/electron/main/code/classes.ts
apps/studio/src/routes/editor/Canvas/Hotkeys/index.tsx

Add ai chat hotkeys

---

apps/studio/electron/main/index.ts

Enforce min width to browser window

---

apps/studio/common/hotkeys.ts
apps/studio/electron/preload/webview/api.ts
apps/studio/electron/preload/webview/elements/index.ts
apps/studio/src/lib/editor/engine/move/index.ts
apps/studio/src/routes/editor/Canvas/Hotkeys/index.tsx

Add movement hotkeys

---

apps/studio/electron/preload/webview/events/dom.ts
apps/studio/src/lib/editor/engine/insert/index.ts
apps/studio/src/lib/editor/engine/overlay/utils.ts
apps/studio/src/lib/editor/engine/text/index.ts
apps/studio/src/lib/editor/eventHandler.ts
apps/studio/src/routes/editor/WebviewArea/GestureScreen.tsx

Fix insert position

---

apps/studio/package.json
packages/foundation/README.md

Publish version v0.1.9

---

apps/studio/electron/main/events/code.ts
apps/studio/src/lib/editor/engine/action/index.ts
apps/studio/src/lib/editor/engine/chat/code.ts
apps/studio/src/lib/editor/engine/chat/index.ts
apps/studio/src/lib/editor/engine/chat/message/assistant.ts
apps/studio/src/lib/editor/engine/code/index.ts
apps/studio/src/lib/editor/engine/history/index.ts
apps/studio/src/routes/editor/EditPanel/StylesTab/single/TailwindInput/index.tsx
packages/foundation/README.md
packages/models/src/actions/action.ts
packages/models/src/actions/code.ts
packages/models/src/chat/message/message.ts
packages/models/src/code/index.ts
packages/models/src/constants/index.ts

Make writing code undo-able

---

apps/studio/package.json
packages/foundation/README.md

Publish version v0.1.10

---

apps/studio/electron/main/events/analytics.ts
apps/studio/electron/main/events/storage.ts
apps/studio/src/components/Context/index.tsx
apps/studio/src/lib/editor/engine/chat/code.ts
apps/studio/src/lib/projects/hosting.ts
apps/studio/src/lib/projects/index.ts
apps/studio/src/lib/user/index.ts
apps/studio/src/routes/editor/Canvas/Hotkeys/Delete.tsx
apps/studio/src/routes/editor/Toolbar/Terminal/index.tsx
apps/studio/src/routes/editor/TopBar/OpenCode/index.tsx
apps/studio/src/routes/editor/TopBar/ShareProject/index.tsx
apps/studio/src/routes/editor/TopBar/index.tsx
apps/studio/src/routes/projects/SettingsTab/index.tsx
apps/studio/src/routes/signin/index.tsx
packages/models/src/constants/index.ts
packages/models/src/projects/index.ts
packages/models/src/settings/index.ts

Add user manager + bug fixes

---

apps/studio/vite.config.ts

Fix vite config error

---

apps/studio/electron/main/hosting/index.ts
apps/studio/package.json
packages/foundation/README.md

Handle zonke api keys not found

---

apps/studio/package.json

Publish version v0.1.11

---

apps/studio/electron-builder.json5
apps/studio/package.json
packages/foundation/README.md

Publish version v0.1.12

---

apps/studio/electron/main/events/hosting.ts
apps/studio/src/routes/projects/ProjectSettingsModal.tsx

Allow updating path string

---

apps/studio/src/routes/editor/TopBar/ProjectSelect/index.tsx
apps/studio/src/routes/projects/ProjectSettingsModal.tsx

Fix project settings commands

---

apps/studio/package.json
packages/foundation/README.md

Publish version v0.1.14

---

apps/studio/electron/preload/webview/api.ts
apps/studio/electron/preload/webview/theme/index.ts
apps/studio/src/routes/editor/EditPanel/WindowSettings/DeviceSettings.tsx
packages/foundation/README.md
packages/foundation/src/create/index.ts

Fix theming

---

apps/studio/electron/preload/webview/api.ts
apps/studio/electron/preload/webview/elements/move/drag.ts
apps/studio/src/lib/editor/engine/move/index.ts
packages/foundation/README.md

Fix buggy drag issue

---

apps/studio/src/lib/editor/engine/chat/conversation/index.ts
apps/studio/src/lib/editor/engine/chat/index.ts
apps/studio/src/lib/editor/engine/chat/stream.ts

Clear chat stream when new conversation started

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md
apps/backend/supabase/config.toml
apps/studio/package.json
apps/studio/src/routes/projects/ProjectsTab/Create/New/Setup.tsx
apps/studio/src/routes/projects/SettingsTab/index.tsx
apps/studio/src/routes/signin/index.tsx
package.json
packages/ai/package.json
packages/cli/package.json
packages/foundation/package.json
packages/models/package.json
packages/supabase/package.json
packages/types/package.json
packages/ui/package.json
packages/utility/package.json
plugins/babel/package.json
plugins/next/Cargo.toml
plugins/next/Cargo.toml.bak
plugins/next/package.json

Update onlook.dev to onlook.com

---

apps/studio/package.json
packages/foundation/README.md

Publish version v0.1.15

---

apps/studio/electron/preload/webview/dom.ts
apps/studio/electron/preload/webview/index.ts

Less refreshes

---

apps/studio/package.json

Publish version v0.1.16

---

apps/studio/src/routes/editor/TopBar/OpenCode/index.tsx

Fix view folder

---

apps/studio/electron/main/code/classes.ts
apps/studio/electron/main/code/diff/index.ts
apps/studio/electron/main/code/files.ts
apps/studio/electron/main/code/index.ts
apps/studio/electron/main/code/templateNode.ts
apps/studio/electron/main/events/code.ts
apps/studio/electron/main/events/run.ts
apps/studio/electron/main/run/cleanup.ts
apps/studio/electron/main/run/process.ts
apps/studio/electron/main/run/setup.ts
apps/studio/src/lib/editor/engine/chat/code.ts
apps/studio/src/lib/editor/engine/code/index.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/MarkdownRenderer.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/CodeChangeDisplay/BashCodeDisplay.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/CodeChangeDisplay/index.tsx
packages/ai/src/coder/block.ts
packages/ai/src/prompt/edit/edit.ts
packages/ai/src/prompt/edit/example.ts
packages/ai/test/prompt/data/examples.txt
packages/ai/test/prompt/data/system.txt
packages/models/src/constants/index.ts

Update code blocks

---

apps/studio/src/lib/editor/engine/chat/conversation/index.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/MarkdownRenderer.tsx

Wrap texts in chat

---

apps/studio/src/routes/editor/Canvas/Hotkeys/index.tsx
apps/studio/src/routes/editor/Canvas/PanOverlay.tsx
apps/studio/src/routes/editor/Canvas/index.tsx
apps/studio/src/routes/editor/EditPanel/WindowSettings/FrameDimensions.tsx
apps/studio/src/routes/editor/TopBar/ZoomControls/index.tsx
apps/studio/src/routes/editor/TopBar/index.tsx
apps/studio/src/routes/editor/WebviewArea/Frame.tsx
apps/studio/src/routes/editor/WebviewArea/ResizeHandles.tsx
apps/studio/src/routes/editor/index.tsx
packages/models/src/constants/index.ts

Fix zooming issue

---

apps/studio/electron/main/hosting/index.ts
apps/studio/src/routes/editor/TopBar/ShareProject/index.tsx

Add a deployment loader

---

apps/studio/src/lib/editor/engine/element/index.ts

Delete instance by default

---

apps/studio/electron/main/run/helpers.ts
apps/studio/electron/main/run/index.ts
apps/studio/src/lib/editor/engine/action/index.ts

Fix dispose build issue

---

apps/studio/common/helpers/twTranslator/index.ts

Fix text-align

---

apps/studio/electron/main/code/files.ts
apps/studio/electron/main/run/helpers.ts
apps/studio/electron/main/run/index.ts
apps/studio/electron/main/run/setup.ts
apps/studio/src/lib/projects/hosting.ts

Fix watcher

---

apps/studio/electron/main/code/diff/image.ts
apps/studio/src/lib/editor/engine/copy/index.ts

Support paste image

---

apps/studio/electron/preload/webview/elements/dom/image.ts
apps/studio/electron/preload/webview/events/index.ts
apps/studio/electron/preload/webview/style/index.ts
apps/studio/src/lib/editor/engine/action/index.ts
apps/studio/src/lib/editor/engine/code/index.ts
apps/studio/src/lib/editor/engine/history/index.ts
apps/studio/src/lib/editor/engine/style/index.ts
apps/studio/src/lib/utils/index.ts
apps/studio/src/routes/editor/EditPanel/StylesTab/compound/NestedInputs.tsx
apps/studio/src/routes/editor/EditPanel/StylesTab/single/ColorInput/ImagePicker.tsx
apps/studio/src/routes/editor/EditPanel/StylesTab/single/ColorInput/index.tsx
apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
packages/models/src/actions/action.ts
packages/models/src/actions/target.ts

Upgrade style system

---

apps/studio/src/lib/editor/engine/image/index.ts

Add image analytics

---

apps/studio/package.json

Publish version v0.1.20

---

apps/studio/electron/main/events/hosting.ts
apps/studio/electron/main/hosting/index.ts
apps/studio/src/lib/projects/hosting.ts
apps/studio/src/routes/editor/Canvas/Overlay/ClickRect.tsx
apps/studio/src/routes/editor/Canvas/Overlay/ResizeHandles.tsx
apps/studio/src/routes/editor/Canvas/Overlay/index.tsx
apps/studio/src/routes/editor/TopBar/ShareProject/index.tsx

Add border radius controller and skip build option

---

apps/backend/supabase/functions/api/index.ts

Access tokens expire, we need to refresh them on the front-end in order to use them to authenticate

Remove auth check on apis for now

---

apps/studio/electron/main/run/helpers.ts

Remove retain lines for more consistent apply

---

apps/studio/electron/main/auth/index.ts
apps/studio/electron/main/events/storage.ts
apps/studio/electron/main/run/helpers.ts
apps/studio/electron/main/storage/index.ts
apps/studio/electron/preload/webview/elements/move/drag.ts
apps/studio/src/lib/editor/engine/move/index.ts
apps/studio/src/routes/editor/WebviewArea/GestureScreen.tsx

bugs: better auth session handling + drag fix

---

apps/studio/src/routes/editor/Canvas/Overlay/index.tsx

Remove memo on hover rects

---

apps/studio/package.json

Publish version v0.1.22

---

.github/workflows/build.yml
apps/studio/electron/main/auth/index.ts
apps/studio/electron/main/events/auth.ts
apps/studio/electron/main/storage/index.ts

Handle auth

---

apps/studio/src/lib/editor/engine/copy/index.ts

Clear clipboard on copy

---

apps/studio/src/lib/editor/engine/index.ts
apps/studio/src/routes/editor/EditPanel/index.tsx

Move chat to default

---

apps/studio/src/routes/editor/TopBar/Profile/PricingPage.tsx

Handle plans returned

---

apps/studio/src/routes/editor/TopBar/Profile/PricingPage.tsx

Update plan page

---

README.md

Swap header image.md

---

apps/studio/package.json

Publish version v0.1.24

---

apps/studio/src/lib/editor/engine/chat/index.ts

Add rate limit analytics

---

apps/studio/electron/main/code/diff/helpers.ts
apps/studio/electron/main/code/diff/index.ts
apps/studio/electron/main/code/files.ts
apps/studio/electron/main/code/index.ts
apps/studio/electron/main/events/code.ts
apps/studio/electron/main/run/cleanup.ts
apps/studio/electron/main/run/helpers.ts
apps/studio/electron/main/run/setup.ts
apps/studio/src/lib/editor/engine/chat/code.ts
apps/studio/src/lib/editor/engine/chat/context.ts
apps/studio/src/lib/editor/engine/code/index.ts
apps/studio/src/lib/editor/engine/overlay/prosemirror/index.ts
packages/models/src/constants/ipc.ts
packages/utility/src/color.ts

Fix losing spacing for formatted code + edit text losing color

---

packages/ai/src/coder/block.ts
packages/ai/src/coder/search_replace.ts
packages/ai/test/coder/search_replace.test.ts
packages/ai/test/prompt/data/system.txt

Better search replace

---

apps/studio/package.json

Publish version v0.1.25

---

apps/studio/src/lib/editor/engine/index.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/index.tsx
apps/studio/src/routes/editor/TopBar/Profile/PricingPage.tsx
apps/studio/src/routes/editor/TopBar/Profile/index.tsx

Plans analytics

---

apps/studio/electron/main/events/index.ts
apps/studio/src/lib/projects/index.ts
apps/studio/src/routes/projects/ProjectsTab/Select/ProjectSettingsButton.tsx
packages/models/src/constants/ipc.ts

Allow move folder to trash on delete

---

apps/studio/package.json

Publish version v0.1.26

---

apps/studio/src/lib/projects/create.ts
apps/studio/src/lib/utils/index.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatInput.tsx
apps/studio/src/routes/projects/PromptCreation/PromptingCard.tsx

Compress prompt images + analytics

---

apps/studio/electron/main/index.ts
apps/studio/electron/main/update/index.ts

Clean up before updating

---

apps/studio/src/routes/projects/ProjectsTab/Create/Load/Setup.tsx
apps/studio/src/routes/projects/ProjectsTab/Create/New/Setup.tsx
packages/foundation/src/setup/index.ts

Allow overriding failed dependencies installation

---

apps/studio/electron/main/create/index.ts

Slightly improve prompt

---

apps/studio/electron/main/chat/index.ts
apps/studio/electron/main/create/index.ts
apps/studio/electron/main/events/create.ts
apps/studio/src/lib/projects/create.ts
apps/studio/src/routes/projects/PromptCreation/CreateError.tsx
apps/studio/src/routes/projects/PromptCreation/CreateLoading.tsx
packages/models/src/constants/ipc.ts

Allow cancellation of prompt creation

---

apps/studio/electron/main/create/index.ts
apps/studio/electron/main/run/index.ts

Update prompt and remove the revert step

---

apps/studio/package.json

Publish version v0.1.27

---

apps/studio/src/routes/editor/EditPanel/ChatTab/CodeChangeDisplay/CollapsibleCodeBlock.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/CodeChangeDisplay/index.tsx
packages/ai/src/coder/block.ts

* Moved some actions out of the bottom of the codeblock (apply / revert)
* Expanded / contracted codeblock

Condensed ai chat

---

apps/studio/package.json

Publish version v0.1.28

---

apps/studio/src/routes/editor/TopBar/Profile/PricingPage.tsx
apps/studio/src/routes/projects/TopBar/index.tsx
packages/ui/src/components/icons/index.tsx

Add plans dropdown to projects select

---

apps/studio/src/routes/editor/EditPanel/StylesTab/index.tsx
apps/studio/src/routes/editor/EditPanel/index.tsx

Potentially address style race condition

---

apps/studio/package.json

Increment version

---

apps/studio/electron/main/run/helpers.ts
apps/studio/src/lib/editor/engine/ast/index.ts
apps/studio/src/routes/editor/LayersPanel/Tree/NodeIcon.tsx
apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
apps/studio/src/routes/editor/WebviewArea/GestureScreen.tsx

Disable selecting body

---

apps/studio/src/routes/editor/TopBar/ProjectSelect/index.tsx
apps/studio/src/routes/editor/TopBar/index.tsx
apps/studio/src/routes/projects/TopBar/index.tsx
packages/ui/src/components/icons/index.tsx

Reorganize the project view top bar

---

apps/studio/electron/main/index.ts
apps/studio/src/lib/editor/engine/error/index.ts

Add cleanup on other quit events

---

apps/studio/src/routes/editor/WebviewArea/Frame.tsx

Ignore renderer errors

---

apps/studio/electron/main/index.ts
apps/studio/package.json

Publish version v0.1.30

---

apps/studio/src/routes/projects/ProjectsTab/index.tsx
apps/studio/src/routes/projects/PromptCreation/index.tsx

Add intial create page page

---

apps/studio/src/routes/editor/EditPanel/ChatTab/ChatInput.tsx
apps/studio/src/routes/projects/PromptCreation/PromptingCard.tsx

Support Japanese input

---

.github/workflows/build.yml
apps/studio/package.json

Publish version v0.1.31

---

apps/studio/src/lib/editor/engine/chat/index.ts
apps/studio/src/lib/editor/engine/error/index.ts
apps/studio/src/lib/editor/engine/webview/index.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/ErrorView/index.tsx
apps/studio/src/routes/editor/WebviewArea/Frame.tsx
packages/ai/test/coder/diffs/diffs.test.ts
packages/utility/src/errors.ts
packages/utility/test/errors.test.ts

1. Hide errors when things are working
2. Handle swc complaints

Improve error messages

---

apps/studio/electron/preload/webview/api.ts
apps/studio/electron/preload/webview/elements/dom/helpers.ts
apps/studio/src/routes/editor/WebviewArea/Frame.tsx

Select first element on start

---

apps/studio/src/routes/editor/WebviewArea/Frame.tsx
packages/ui/src/components/shine-border.tsx
packages/ui/tailwind.config.ts

Add play and wait states

---

apps/studio/package.json

Release 0.1.32

---

apps/studio/package.json
apps/studio/src/routes/editor/TopBar/Profile/PricingPage.tsx

Save basic plan as well

---

apps/studio/package.json

Publish version v0.1.33

---

apps/studio/electron/main/auth/index.ts
apps/studio/electron/main/index.ts

https://supabase.com/docs/reference/javascript/auth-startautorefresh

Add auth auto-refresh per Supabase recommendations

---

apps/studio/electron/main/index.ts

App cleaning up when it should not on Mac

---

apps/studio/src/routes/editor/EditPanel/ChatTab/ErrorView/index.tsx

Fix error button in light mode

---

apps/studio/package.json

Release version v0.1.34

---

apps/studio/src/lib/projects/index.ts
apps/studio/src/routes/projects/ProjectsTab/Create/Load/SetUrl.tsx
apps/studio/src/routes/projects/ProjectsTab/Create/index.tsx

Closes: #1200 
This PR addresses an issue where the installation script was not executing updated command correctly when importing the project

Fix: Resolve install script issue during project import

---

apps/studio/src/routes/projects/ProjectsTab/Create/Load/Setup.tsx
apps/studio/src/routes/projects/ProjectsTab/Create/Load/Warning.tsx
apps/studio/src/routes/projects/ProjectsTab/Create/stepContents.tsx
packages/ui/src/components/icons/index.tsx
packages/ui/src/components/toast.tsx

Closes: #1135
This PR introduces a new warning toast notification that informs users about the behavior of (OIDs) during the import process.

feat: Add warning toast for OID import notification

---

apps/studio/package.json

Publish version v0.1.36

---

apps/studio/src/routes/projects/ProjectsTab/Create/index.tsx

-  Once you've completed the import process, run the project.

feat: importing project should start running after complete

---

apps/studio/src/routes/editor/EditPanel/ChatTab/Suggestions/index.tsx
bun.lock

- If there is a breaking error, hide the suggestions
closes #1235

feat: hide suggestions if there is a breaking error

---

apps/studio/package.json

Publish version v0.1.37

---

apps/studio/electron/main/analytics/index.ts
apps/studio/electron/main/events/storage.ts
apps/studio/src/routes/editor/TopBar/Profile/PricingPage.tsx
packages/models/src/constants/ipc.ts
packages/models/src/settings/index.ts

Get more visibility on errors
related to #1255

Update analytics with architecture information

---

.github/workflows/build.yml
apps/studio/.gitignore
apps/studio/electron/main/bun/index.ts
apps/studio/package.json

Update bun build

---

apps/studio/package.json

Publish version v0.1.38

---

apps/studio/electron/main/bun/parse.ts
apps/studio/package.json
bun.lock
scripts/download_bun.ts

Publish version v0.1.40

---

apps/studio/src/lib/editor/engine/chat/index.ts
apps/studio/src/lib/editor/engine/error/index.ts

Fix multiple inputs at the same time

---

apps/studio/electron/main/bun/index.ts
apps/studio/electron/main/run/terminal.ts

Disable Bun for intel Mac

---

apps/studio/package.json

Publish version v0.1.41

---

.github/workflows/build.yml
apps/studio/builder-config/base.ts
apps/studio/builder-config/darwin-arm64.ts
apps/studio/builder-config/darwin-x64.ts
apps/studio/electron/main/bun/index.ts
apps/studio/electron/main/create/install.ts
apps/studio/electron/main/run/terminal.ts
apps/studio/package.json
packages/ai/src/prompt/format.ts
packages/ui/src/components/use-toast.tsx

Update CI/CD for config

---

apps/studio/package.json

Publish version v0.1.42

---

apps/studio/src/lib/editor/engine/chat/context.ts
apps/studio/src/lib/editor/engine/chat/index.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatInput.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/index.tsx

Fix images and screenshots

---

apps/studio/package.json
bun.lock

Publish version v0.1.43

---

apps/studio/src/lib/editor/engine/chat/index.ts

Clean up test 

---

apps/studio/package.json

Publish version v0.1.44

---

apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx

Update window selected style

---

apps/studio/src/lib/editor/engine/chat/index.ts

Apply code by default

---

apps/studio/package.json
apps/studio/src/routes/editor/TopBar/ProjectSelect/index.tsx

Reenable subscriptions page

---

apps/studio/electron/main/bun/index.ts
apps/studio/electron/main/create/install.ts
apps/studio/electron/main/create/setup.ts
apps/studio/electron/main/events/create.ts
apps/studio/electron/main/hosting/helpers.ts
apps/studio/electron/main/hosting/index.ts
apps/studio/electron/main/run/terminal.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/CodeChangeDisplay/BashCodeDisplay.tsx
packages/models/src/bun/index.ts
packages/models/src/index.ts

Better bun command api

---

apps/studio/package.json

Publish version v0.1.48

---

apps/studio/electron/main/events/page.ts
apps/studio/electron/main/pages/index.ts
apps/studio/src/lib/editor/engine/pages/index.ts
apps/studio/src/routes/editor/LayersPanel/Tree/PageTreeNode.tsx
apps/studio/src/routes/editor/LayersPanel/index.tsx
packages/models/src/constants/ipc.ts

This PR introduces the following changes:
1. Feature: Delete Page Functionality
2. Fix: Dynamic Route Highlighting
3. Fix: Grouped Route Navigation

feat: Refactor page tab

---

packages/ai/src/prompt/edit/edit.ts
packages/ai/src/prompt/shell.ts
packages/ai/test/prompt/data/system.txt

Update system prompt

---

apps/studio/electron/preload/webview/dom.ts
apps/studio/electron/preload/webview/elements/dom/group.ts
apps/studio/electron/preload/webview/elements/dom/helpers.ts
apps/studio/electron/preload/webview/elements/dom/insert.ts
apps/studio/electron/preload/webview/elements/dom/remove.ts
apps/studio/electron/preload/webview/elements/helpers.ts
apps/studio/electron/preload/webview/elements/move/drag.ts
apps/studio/electron/preload/webview/elements/move/index.ts
apps/studio/electron/preload/webview/elements/text.ts
apps/studio/electron/preload/webview/events/publish.ts
apps/studio/electron/preload/webview/index.ts
apps/studio/electron/preload/webview/style/index.ts

Change error to warn in preload

---

apps/studio/electron/main/index.ts
apps/studio/package.json
apps/studio/src/routes/editor/LayersPanel/index.tsx
bun.lock

Upgrade electron and remove cleanup step

---

apps/studio/src/routes/editor/TopBar/ProjectSelect/index.tsx
apps/studio/src/routes/projects/ProjectsTab/Select/ProjectSettingsButton.tsx

Change open project folder wording

---

apps/studio/electron/main/index.ts

Remove unneeded clean up steps

---

apps/studio/electron/main/update/index.ts

Remove cleanup

---

apps/studio/package.json

Publish version v0.1.50

---

apps/studio/electron/main/create/index.ts
apps/studio/electron/main/events/create.ts
apps/studio/src/lib/projects/create.ts
apps/studio/src/routes/projects/PromptCreation/PromptingCard.tsx
packages/models/src/constants/ipc.ts
packages/models/src/create/index.ts

Start from blank template

---

apps/studio/src/lib/editor/engine/chat/stream.ts
apps/studio/src/routes/editor/TopBar/ProjectSelect/SettingsModal/index.tsx
apps/studio/src/routes/editor/TopBar/ProjectSelect/index.tsx

Fix the settings modal

---

apps/studio/src/lib/editor/engine/index.ts
apps/studio/src/routes/editor/EditPanel/ChatTab/CodeChangeDisplay/CollapsibleCodeBlock.tsx
apps/studio/src/routes/editor/SettingsModal/index.tsx

Hide domains settings

---

apps/studio/package.json

Release 0.2

---

apps/studio/electron/main/code/diff/group.ts
apps/studio/electron/main/code/diff/insert.ts
apps/studio/electron/preload/webview/elements/dom/remove.ts
apps/studio/src/lib/editor/engine/code/index.ts
apps/studio/src/lib/editor/engine/code/insert.ts
apps/studio/src/lib/editor/engine/copy/index.ts
apps/studio/src/lib/editor/engine/element/index.ts
apps/studio/src/lib/editor/engine/insert/index.ts
apps/studio/src/routes/editor/LayersPanel/index.tsx
packages/models/src/actions/action.ts
packages/models/src/actions/code.ts

- Fix issue when undo/redo action deleting an image
close #867 
https://github.com/user-attachments/assets/54826be1-0f21-458b-a2db-75e78c1d231c

fix: issue when undo and redo with image action

---

apps/studio/electron/main/pages/index.ts

Add new page to watcher

---

CONTRIBUTING.md

fix a tiny typo in CONTRIBUTING.md

fix(docs): fix a tiny typo in CONTRIBUTING.md

---

apps/studio/src/routes/editor/SettingsModal/ProjectTab.tsx

Add select path button in settings

---

apps/studio/package.json
bun.lock

Upgrade node-pty

---

apps/studio/package.json

Publish version v0.2.2

---

apps/studio/src/routes/editor/EditPanel/ChatTab/ChatInput.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/UserMessage.tsx

Fix chat input composing regression

---

apps/studio/package.json

Publish version v0.2.3

---

apps/studio/electron/main/events/hosting.ts
apps/studio/electron/main/hosting/domains.ts
apps/studio/electron/main/hosting/index.ts
apps/studio/src/lib/editor/engine/index.ts
apps/studio/src/routes/editor/SettingsModal/Domain/Verification.tsx
apps/studio/src/routes/editor/SettingsModal/index.tsx
packages/foundation/src/utils.ts
packages/models/src/constants/api.ts
packages/models/src/constants/freestyle.ts
packages/models/src/constants/index.ts
packages/models/src/constants/ipc.ts
packages/models/src/hosting/index.ts
packages/models/src/supabase/db.ts

Support linking custom domains

---

apps/studio/src/lib/projects/domains/index.ts
apps/studio/src/lib/projects/index.ts
apps/studio/src/routes/editor/SettingsModal/Domain/Custom/Verification.tsx
apps/studio/src/routes/editor/SettingsModal/Domain/Custom/Verified.tsx

Verifying and adding custom domain pt.3

---

apps/studio/src/routes/projects/ProjectsTab/Create/Load/Warning.tsx

Update import warning

---

apps/studio/src/lib/projects/port.ts

Fix port taken appearing on error

---

apps/studio/electron/main/create/index.ts
apps/studio/src/lib/projects/create.ts

Update wait time messages

---

apps/studio/src/routes/editor/WebviewArea/BrowserControl/index.tsx
bun.lock
packages/utility/package.json
packages/utility/src/urls.ts

Update and normalize urls

---

apps/studio/package.json

Publish version v0.2.5

---

apps/studio/src/lib/editor/engine/insert/index.ts

Make inserted elements absolute

---

apps/studio/package.json

Publish version v0.2.7

---

apps/studio/src/routes/editor/EditPanel/StylesTab/index.tsx

Translation bug

---

apps/studio/src/lib/editor/engine/chat/helpers.ts

Handle context length message 3.7

---

apps/studio/package.json
apps/studio/src/routes/editor/HotkeysModal/index.tsx

Publish version v0.2.8

---

apps/studio/electron/main/code/files.ts
apps/studio/electron/main/pages/create.ts
apps/studio/electron/main/run/index.ts

This reverts commit c525b3babf8241b2a95bdd5686901390014a280d.

Revert "feat: watch file changes in directory (#1478)"

---

apps/studio/src/routes/editor/DevTab/index.tsx
apps/studio/src/routes/editor/EditPanel/DevTab/index.tsx
apps/studio/src/routes/editor/EditPanel/index.tsx
packages/ui/src/components/resizable.tsx

Created a panel for a code editor and file manager dropdown.
Here's the base of what we're building:
**Top Bar**
1. In the "Edit Code" dropdown menu, add an optional toggle to "Jump to code from canvas":
When a user clicks an element on the canvas this function should locate/show where that element is in the code editor
2. In the "Files" dropdown menu add a file tree, with a search function on top, and buttons to add a new page and folder:
3. When right-clicking a file, create these options in the context menu:
4. When right-clicking a folder, create these options in the context menu:
**Opened Tabs / Navigation Bar**
1. When a file is opened in the editor, display this Active state:
2. When a tab is hovered, show this Hover state with the "x" to remove the file from the navigation bar if …

Tys editor - DevTab

---

apps/studio/src/routes/editor/LayersPanel/WindowsTab/FrameDimensions.tsx

Handle potential null accessors

---

apps/studio/electron/main/events/hosting.ts
apps/studio/src/routes/editor/SettingsModal/Domain/Custom/Verification.tsx

Add custom domains analytics

---

apps/studio/src/routes/editor/SettingsModal/Domain/DangerZone.tsx

Allow unpublishing domain

---

apps/studio/src/routes/editor/SettingsModal/Domain/Custom/Verification.tsx

Update verify domain button text

---

scripts/download_bun.ts

Upgrade bun version to 1.2.4

---

apps/studio/src/lib/editor/engine/element/index.ts
apps/studio/src/routes/editor/Canvas/Overlay/ClickRect.tsx
apps/studio/src/routes/editor/Canvas/Overlay/ResizeHandles.tsx

Adaptive resize handlers

---

apps/studio/src/routes/editor/SettingsModal/Domain/Custom/Verification.tsx
bun.lock
packages/utility/package.json
packages/utility/src/urls.ts

Better domain validation

---

apps/studio/src/routes/editor/EditPanel/ChatTab/ChatControls/ChatHistory.tsx
apps/studio/src/routes/editor/EditPanel/ChatTab/ChatControls/index.tsx
apps/studio/src/routes/editor/EditPanel/index.tsx
apps/studio/src/routes/editor/SettingsModal/Versions/VersionRow.tsx
apps/studio/src/routes/editor/SettingsModal/Versions/Versions.tsx

Tys version styles

---

apps/studio/src/routes/editor/SettingsModal/Versions/VersionRow.tsx

Fix renaming issue for backup

---

apps/studio/electron/main/events/versions.ts
apps/studio/src/lib/editor/engine/chat/code.ts
apps/studio/src/lib/editor/engine/chat/conversation/index.ts
apps/studio/src/lib/editor/engine/chat/index.ts
apps/studio/src/lib/projects/versions.ts
apps/studio/src/routes/editor/SettingsModal/Versions/VersionRow.tsx
apps/studio/src/routes/editor/SettingsModal/Versions/Versions.tsx
packages/git/src/git.ts
packages/git/test/git.test.ts
packages/models/src/constants/ipc.ts

Autosave before applying code and restoring backup

---

apps/studio/package.json
apps/studio/src/routes/editor/SettingsModal/Versions/VersionRow.tsx

Publish version v0.2.9

---

apps/studio/src/routes/editor/SettingsModal/Versions/VersionRow.tsx
apps/studio/src/routes/editor/SettingsModal/Versions/Versions.tsx

Updated with dividers, full width layout, slightly modified version hover state

Tys version styles v2

---

apps/studio/electron/preload/browserview/index.ts

Reset zoom level on render

---

apps/studio/package.json

Publish version v0.2.10

---

apps/studio/package.json

Publish version v0.2.11

---

apps/studio/src/routes/editor/TopBar/ProjectSelect/index.tsx

Ensure project stops and add waiting state

---

apps/studio/src/routes/editor/SettingsModal/Project/index.tsx

Fix spelling mistake

---

apps/web/client/src/components/store/editor/font/index.ts
packages/db/src/dto/message.ts

Clean up after conversation

---

apps/web/client/src/env.ts
docs/content/docs/developer/running-locally.mdx
packages/scripts/src/index.ts

1. Fixed the incorrect command in 7th step of docs for seeding the database.
2. Fixed the zod verification for anthropic api key as it was missing the optional attribute.
None
None
None

Fixed a documentation typo and zod verification bug

---

apps/web/client/src/app/project/[id]/_components/editor-bar/text-selected.tsx
apps/web/client/src/app/project/[id]/_hooks/use-chat.tsx
apps/web/client/src/components/store/editor/font/index.ts

update text edit tooltip

---

README.md

docs: restore old header

---

docs/content/docs/index.mdx

Use a more relevant video for getting started.

docs: update docs get started video

---

apps/web/client/src/app/project/[id]/_components/editor-bar/index.tsx
apps/web/client/src/components/store/editor/ast/index.ts
apps/web/client/src/components/store/editor/image/index.ts
apps/web/client/src/components/store/editor/sandbox/terminal.ts
apps/web/client/src/server/api/routers/invitation.ts

chore: fix typecheck for unused code

---

apps/web/client/src/app/project/[id]/_components/canvas/frame/index.tsx
apps/web/client/src/app/project/[id]/_components/left-panel/windows-tab/frame-dimensions.tsx
apps/web/client/src/components/store/editor/frames/index.ts

fix: frame not moving

---

apps/web/client/src/app/project/[id]/_components/canvas/frame/index.tsx

feat: add top bar right click menu

---

apps/web/client/src/app/project/[id]/_components/right-panel/chat-tab/code-change-display/bash-code-display.tsx
packages/ai/src/prompt/context.ts
packages/ai/src/prompt/shell.ts
packages/ai/test/prompt/data/create-page-system.txt
packages/ai/test/prompt/data/system.txt
packages/ai/test/prompt/data/user.txt

The AI chat was suggesting npm install commands that failed in the CodeSandbox environment with "command not found: npm" errors. This was causing a poor user experience where AI-suggested package installations wouldn't work.
The project uses Bun as the package manager (as configured in .codesandbox/tasks.json with "setupTasks": ["bun install"]), but the AI system prompts were explicitly instructing the AI to suggest npm commands:
Updated AI system prompts to instruct the AI to use Bun commands instead of npm:
Context prompts: Changed error handling instructions from npm install → bun install
Shell prompts: Added comprehensive Bun command mappings
Command translations:
npm install → bun install
npm install <package> → bun add <package>
npm run <script> → bun run <script>
npx <command> → …

fix: installation from chat issue

---

apps/web/preload/dist/index.js

fix: include preload script

---

apps/web/client/src/app/project/[id]/_components/right-panel/index.tsx

fix: keep dev tab mounted to continue subscribing to file changes

---

apps/web/client/src/app/project/[id]/_components/canvas/frame/top-bar.tsx
apps/web/client/src/app/project/[id]/_components/editor-bar/index.tsx

fix: top bar visual bug

---

apps/web/client/src/app/project/[id]/_components/editor-bar/overflow-menu.tsx

fix: drag extend

---

apps/web/client/src/server/api/routers/usage/index.ts

bugs: update usage count start date

---

apps/web/client/src/components/tools.ts

refactor: tools type safety

---

apps/web/client/src/server/api/routers/subscription/subscription.ts

refactor: only log no subscription

---

apps/web/client/src/app/project/[id]/_components/main.tsx

fix: overflow scroll

---

apps/web/client/src/app/api/chat/helpers/stream.ts
apps/web/client/src/app/project/[id]/_components/right-panel/chat-tab/chat-messages/message-content/index.tsx
apps/web/client/src/app/project/[id]/_components/right-panel/chat-tab/chat-messages/stream-message.tsx

feat: reasoning ui improvements
