README.md
Super minor changes, but just something I ran into.
- Fix "View Demo" link (might be eaiser to just link directly to video)
- User should be able to execute all the commands verbatim to run the project
=> Fix: Udpate demo link and add 'studio' to cd command

demos/next/package.json
When running the Next.js example on Windows. `rm -rf .next` fails because it's not a Powershell/Bash command. I fixed this by adding `rimraf` to the dev dependecies of the Next.js demo project and used that to remove the `.next` folder
=> use rimraf to remove .next folder

app/src/lib/editor/engine/code/index.ts, app/src/routes/project/LayersPanel/LayersTab.tsx, app/src/routes/project/SharePopver/index.tsx
Fix Main window api broken by last release
=> [BUG] Fix Main window api broken by last release

app/common/constants.ts, app/electron/preload/webview/elements/helpers.ts, app/electron/preload/webview/events.ts, app/src/lib/editor/engine/ast/index.ts, app/src/lib/editor/engine/ast/map.ts, app/src/lib/editor/engine/dom/index.ts, app/src/lib/editor/eventHandler.ts
Refresh layers when the DOM is mutated. This way the layers can keep up with changing DOM.
=> Refresh layers when the DOM is mutated

app/package.json, app/scripts/publish_tag.sh
=> Publish version v0.0.13

app/src/routes/project/RightClickMenu/index.tsx
When we select a component we have the `instance` information but when we select any non-components it's `undefined`, used that logic to differentiate between elements and components.
Fixes #251
=> fix: for non-components show text "View element code" on right click

app/electron/preload/webview/api.ts, app/src/lib/editor/engine/index.ts, app/src/routes/project/RightClickMenu/index.tsx
Allow the ability to manually refresh layers. For situations where animation happens that changes the page drastically.
=> Add refresh layer escape hatch

app/src/components/ui/tooltip.tsx, app/src/routes/editor/LayersPanel/Tree/TreeNode.tsx
This PR fixes #360 
I removed the animations from the tooltip component itself and now they appear at the same time. 
I also added a slight animation for the text so that it doesn't jump into focus when the tooltip animates (this is just a small quality of life improvement). 
https://github.com/user-attachments/assets/2a10901e-5cec-4381-a8a5-5d2e6a161b8d
This PR fixes this issue #360 
This is a demo of
=> :bug: fixed lag in the long layer name animation tooltip 

app/common/tokens.js, app/src/components/ui/button.tsx, app/src/components/ui/card.tsx, app/src/lib/routes/index.ts, app/src/routes/projects/ProjectsTab/Create.tsx, app/src/routes/projects/ProjectsTab/Create/LoadProject.tsx, app/src/routes/projects/ProjectsTab/Create/NewProject.tsx, app/src/routes/projects/ProjectsTab/Create/index.tsx, app/src/routes/projects/ProjectsTab/index.tsx, app/src/routes/projects/SettingsTab/index.tsx, app/tailwind.config.mjs
=> New Project + Settings page UI

demos/remix/README.md
The changes made only to the Onlook configuration on Vite projects. Made some style changes (add headers of 2nd and 3rd level) and add one more step with images to show, how to open the project inside Onlook. It has been done, because I had a problem understanding, how to use Onlook correctly, so by this commit I'm removing the fog a little bit.
=> Add one more step for configuring Onlook in Vite projects

app/bunfig.toml, app/package.json
I have used Bun’s built-in coverage support for test coverage tracking, which generates reports and provides insights into how much of your code is covered by tests.
=> feat: Add unit test coverage tracking

app/common/constants.ts, app/electron/preload/webview/elements/move/drag.ts, app/electron/preload/webview/elements/text.ts, app/src/lib/editor/engine/code/index.ts, app/src/routes/editor/TopBar/OpenCode/index.tsx, app/src/routes/editor/TopBar/PublishModal/index.tsx
=> Highlight write to code

app/common/ide.ts
This PR re-enables the Zed integration by addressing a specific edge case: it only appends the start line and column to the URL when the URL is specifically for Zed and not the end line and column _(see zed-industries/zed#18520 for more info)_
Closes #415
=> Enable start line and column for Zed only

app/electron/preload/webview/api.ts, app/electron/preload/webview/theme/index.ts, app/src/routes/editor/WebviewArea/BrowserControl.tsx, app/src/routes/editor/WebviewArea/Frame.tsx
dark mode toggle (browser top-right corner):
it's works perfectly with new feature tailwind input. `bg-blue-900 dark:bg-blue-300`
=> darkmode preview

app/src/routes/editor/Canvas/index.tsx
Related to issue #307 
Previously, the react "window" inside the app, done with a <webview>, would be off center when onlook was quit with it off center and then reopened. This was because position was only being reset once the app was fully quit and the cache cleared. Now, the react "window" is reset each time onlook is reopened. I did not address the fact that scaling persists through closing and opening onlook because this was not what the issue was about, but changing that would require minimal edits right next to where my edits were made.
=> webview issue

app/src/index.css
This PR addresses issue #278, where holding down the Shift key and clicking on elements in the UI occasionally adds a white border around those elements. This behavior is unintended and should not occur in the Onlook UI.
The issue occurs because of the `:focus-visible` pseudo-class which applies while an element matches the `:focus` pseudo-class and the UA determines via heuristics that the focus should be made evident on the element. Many browsers show a "focus ring" by default in this case, which is removed in this PR.
Although this fixes the issue of unintended white outline on shift click, it also removes the white outline on tab click which makes it harder to navigate the UI using the keyboard.
=> Fix: Prevent white outline when holding shift and clicking on UI elements

app/common/actions.ts, app/src/index.css, app/src/lib/editor/engine/action/index.ts, app/src/lib/editor/engine/history/index.ts, app/src/lib/editor/engine/index.ts, app/src/lib/editor/engine/style/index.ts, app/src/lib/editor/styles/group.ts, app/src/routes/editor/EditPanel/inputs/compound/BorderInput.tsx, app/src/routes/editor/EditPanel/inputs/compound/GridRowColInput.tsx, app/src/routes/editor/EditPanel/inputs/compound/NestedInputs.tsx, app/src/routes/editor/EditPanel/inputs/single/AutoLayoutInput.tsx, app/src/routes/editor/EditPanel/inputs/single/ColorInput/index.tsx, app/src/routes/editor/EditPanel/inputs/single/NumberUnitInput.tsx, app/src/routes/editor/EditPanel/inputs/single/SelectInput.tsx, app/src/routes/editor/EditPanel/inputs/single/TextInput.tsx
=> Multi-select with correct element history

app/src/assets/word-logo.svg, app/src/components/Announcement/index.tsx, app/src/components/ui/logo.tsx, app/src/routes/projects/TopBar/index.tsx, app/src/routes/signin/index.tsx
Fix #531.
- I've created `WordLogo` component for better code maintainability
- Refactored `Announcement`, `TopBar`, and `SignIn` components to use the new `WordLogo` component instead of direct image imports
This could be solved by simply adding a class to the <img/> tag, but creating this component allows us to easily transform other images into components as well.
=> Make the logo the proper foreground color for light / dark mode

app/src/routes/projects/ProjectsTab/Select/Carousel.tsx, app/src/routes/projects/ProjectsTab/Select/EditAppButton.tsx, app/src/routes/projects/ProjectsTab/Select/Info.tsx
Link to issue: https://github.com/onlook-dev/onlook/issues/532
Add a hover state over the projects showing an "Edit App" button with clean animation.
https://github.com/user-attachments/assets/99839212-5cc2-4e1c-b1d2-c453a0738285
=> feat: add hover on EmblaCarousel to show edit button

app/src/routes/editor/TopBar/ProjectSelect/index.tsx
Link to issue: https://github.com/onlook-dev/onlook/issues/543
When the project menu is opened, animate and rotate the arrow icon 180º to point up.
https://github.com/user-attachments/assets/5777e5f8-85cf-46a9-afa0-2b49a9df2662
=> chore: handle rotate chevron icon when open dropdown menu

app/src/routes/projects/ProjectsTab/Create/New/Run.tsx
Fix #547 
- just add the [`/d` param](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cd#parameters) to cd command in windows.  
- > `/d` Changes the current drive as well as the current directory for a drive.
=> Command to run a new project on Windows 

app/src/routes/projects/ProjectsTab/Select/ProjectSettingsButton.tsx
@drfarrell  can you please add Labels on this for hacktoberfest-accepted? Thanks.
https://github.com/onlook-dev/onlook/issues/569
This PR addresses a bug where the rename input field fails to update when switching between projects. The input field is now properly refreshed upon project selection, ensuring that the correct project name is displayed in the rename field.
=> [bug] Rename input needs to be refreshed when a new project is selected

app/src/routes/editor/EditPanel/inputs/single/TailwindInput.tsx
As per issue https://github.com/onlook-dev/onlook/issues/549, the 'textArea' where a user can input tailwind classes for an object needed a hint or message at the bottom saying "enter to apply" when the object is in focus. This is done to let the user know that while in focus, changes may not be saved, and to save changes they must click the enter key.
I was provided with that piece of information, as well as an SVG for an arrow ![image](https://github.com/user-attachments/assets/d14c0157-7f89-45e9-8141-12b5b99422d1), and a reference picture: 
My current implementation looks as so:
I was able to implement this feature, albeit with some minor changes to the textArea.  Currently it is being auto resized with the user's text and some extra space as the sizing option.
Was informed by …
=> Text area focus hint

app/src/components/ui/popover.tsx, app/src/routes/editor/WebviewArea/BrowserControl.tsx
=> Use correct token for preset window

app/src/assets/zed.svg
fix #583 
- Changes `zed.svg` to a silver color palette to be visible in both dark and light mode
=> Update zed.svg to work in light and dark mode

app/electron/preload/webview/elements/move/helpers.ts, app/electron/preload/webview/elements/move/stub.ts
The code has been updated to support grid layouts in addition to the existing flex and block layout handling. This was achieved by modifying the moveStub function to detect grid layouts and apply specialized handling. Two new functions, findGridInsertionIndex and adjustStubPositionForGrid, were introduced to calculate insertion positions and correctly position the stub within grid cells, respectively.
with code correct
- [ X] New feature
- [X ] Bug fix
=> Add grid drag-and-drop support

app/src/routes/editor/EditPanel/StylesTab/index.tsx, app/src/routes/editor/EditPanel/index.tsx, app/src/routes/editor/LayersPanel/index.tsx
While opening or closing the `EditPanel` tab, the content inside was overflowing beyond the boundaries of the panel. This caused the UI to break during animations.
We applied **`overflow-hidden`** to critical containers and added **width/height constraints** to prevent content from escaping during transitions. We also ensured smooth transitions with CSS adjustments.
1. **Apply `overflow-hidden` to the Main Wrapper:**
- Ensures that the content stays within the panel boundaries during open/close transitions.
```jsx
<div
className={clsx(
'fixed right-0 transition-width duration-300 opacity-100 bg-background/80 rounded-tl-xl overflow-hidden',
editorEngine.mode === EditorMode.INTERACT ? 'hidden' : 'visible',
!isOpen && 'w-12 h-12 rounded-l-xl cursor-pointer',
isOpen && 'h-[calc(100vh-5rem)]', …
```
=> Debugged Properties panel close Animation Bug

packages/ui/src/components/color-picker/ColorPicker.tsx
Added `activeHue` & `localColor` state & optimized onChange functions to maintain the selected hue value independently from the color's calculated hue, it allows hue persistence even at low saturation levels which solved the bug issue when selecting colors far left.
1.  Separated hue tracking from color state
2. Always use `ActiveHue` when creating new colors
3. Persist hue value during saturation changes
Related: https://github.com/onlook-dev/onlook/issues/699
=> Fix: Changing colors while hue is all the way left not working

apps/studio/src/lib/editor/engine/overlay/index.ts, apps/studio/src/routes/editor/WebviewArea/Frame.tsx, packages/ui/src/components/icons/index.tsx
Link to issue: https://github.com/onlook-dev/onlook/issues/619
Ability for a user to select the top of the browser controls and drag the selected window around the infinite canvas. 
https://github.com/user-attachments/assets/79666d99-c8b1-40ac-b513-e333bd8b81a7
=> feat: handle drag the broweser canvas

apps/studio/src/routes/editor/TopBar/ZoomControls/index.tsx
The input loses focus on hover because of dropdown. Use popover instead solves this.
=> Use popover instead of dropdown for zoom control

apps/studio/electron/main/events/run.ts, apps/studio/electron/main/run/index.ts, apps/studio/src/lib/projects/run.ts, apps/studio/src/routes/editor/Toolbar/Terminal/RunButton.tsx, packages/foundation/src/frameworks/remove.ts, packages/foundation/src/index.ts, packages/foundation/src/revert/index.ts, packages/foundation/tests/revert.test.ts, packages/models/src/constants/index.ts
Support running legacy projects by running a remove script on start. This will remove the Onlook plugins from configs and package.json files.
=> Remove legacy onlook plugins on start

apps/studio/src/lib/editor/engine/chat/conversation.ts
Previously, we were stripping down the users' past messages to save cost. But this can cause issue so we'll just pass the full history context to the model and eat the cost.
=> Don't strip messages from users messages

apps/studio/package.json, apps/studio/src/routes/editor/LayersPanel/Tree/TreeNode.tsx, packages/foundation/README.md
=> Publish version v0.1.5

apps/studio/src/routes/editor/TopBar/ZoomControls/index.tsx
This PR addresses an issue where the input field did not reflect the latest scale value from the `editorEngine`. Instead, it displayed outdated values, leading to confusion for users when interacting with the editor.
=> fix: Update zoom input value to reflect latest zoom scale value

apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/StreamMessage.tsx, apps/studio/src/routes/editor/EditPanel/ChatTab/CodeChangeDisplay/BashCodeDisplay.tsx
=> Fix not clickable outside of stream

apps/studio/src/routes/projects/PromptCreation/PromptingCard.tsx
This PR addresses a bug that prevented users from re-uploading an image after it was removed in the "create new project" section.
=> fix: resolve issue with re-uploading removed images in create new project section

apps/studio/src/routes/editor/Toolbar/Terminal/index.tsx, packages/models/src/constants/index.ts, packages/models/src/constants/terminal.ts, packages/models/src/run/index.ts
This PR introduces functionality to detect when a user interrupts the terminal session by pressing Ctrl+C, and it ensures that the current running manager exits appropriately
=> Fix: Detect Ctrl+C Interrupt in Terminal

apps/studio/src/lib/projects/create.ts
- Add timer to detect slow project creation (>30s)
- Show helpful message when connection might be slow
- Properly handle timer cleanup to prevent memory leaks
Closes #1192
This PR adds a helpful message to inform users when project creation is taking longer than expected. After 10 seconds of loading, if the project hasn't finished creating, we show a message suggesting that the delay might be due to a slow internet connection. The timer is properly managed to avoid memory leaks and is automatically cleaned up when the component is unmounted or when the loading state changes.
=> feat: add slow connection message during project creation

apps/studio/src/routes/editor/Toolbar/Terminal/index.tsx
Fix the issue where the last line of the terminal disappears after multiple commands have been entered
Fixes #1291 
I typed in multiple commands before and after the change and adding the change fixed the issue.
=> Change overflow-hidden to overflow-auto

apps/studio/electron/main/assets/index.ts, apps/studio/electron/main/events/asset.ts, apps/studio/electron/main/events/index.ts, apps/studio/package.json, apps/studio/src/lib/editor/engine/chat/index.ts, apps/studio/src/lib/editor/engine/image/index.ts, apps/studio/src/lib/editor/engine/index.ts, apps/studio/src/lib/editor/engine/webview/index.ts, apps/studio/src/routes/editor/LayersPanel/ImagesTab.tsx, apps/studio/src/routes/editor/LayersPanel/index.tsx, bun.lock, packages/models/src/constants/ipc.ts, packages/ui/src/components/icons/index.tsx
Currently, these features below are built and hidden on the LayersPanel side
- Scan for the standard Next.js assets folder and find any images that can be used and loaded images into the sidepanel
- Allowed the ability to add image which will put it in the expected next.js standard folder
- Added a search bar that just filters based on filename
- Related to #1241
https://github.com/user-attachments/assets/b6adaf45-8b15-4fd8-9963-9230b50d0a7e
=> feat: add assets management

apps/studio/src/lib/editor/engine/element/index.ts
Closes: #1350
This PR addresses an issue where only a single selected element was deleted, even when multiple elements were selected. The `delete()` function has been updated to iterate through all selected elements, enabling bulk deletion.
=> fix: Enable deletion of multiple selected elements

apps/studio/src/lib/editor/engine/canvas/index.ts, apps/studio/src/lib/editor/engine/index.ts, apps/studio/src/routes/editor/Canvas/Hotkeys/Delete.tsx, apps/studio/src/routes/editor/EditPanel/ChatTab/ChatMessages/UserMessage.tsx, apps/studio/src/routes/editor/EditPanel/WindowSettings/index.tsx, apps/studio/src/routes/editor/RightClickMenu/index.tsx, apps/studio/src/routes/editor/WebviewArea/BrowserControl/index.tsx, packages/models/src/constants/editor.ts, packages/models/src/projects/index.ts
This PR addresses an issue where users could select the main window and then attempt to delete it, which would result in a no-op. This behavior was misleading and could lead users to believe the application was not functioning correctly.
=> Fix: Hide delete options in main window

apps/studio/electron/preload/webview/elements/dom/group.ts, apps/studio/src/lib/editor/engine/ast/index.ts, apps/studio/src/lib/editor/engine/copy/index.ts, apps/studio/src/lib/editor/engine/group/index.ts
- When user copy and paste nested elements, it makes the layer tree messed up sometimes
-  Root-cause:  Does not provide a fresh element for children in 
- fixes #994 
https://github.com/user-attachments/assets/0ca4e216-ab66-4e64-a0a6-cadcb6f7072f
=> fix: messed up layer tree when copy/group/ungroup nested element

apps/studio/src/lib/projects/domains/hosting.ts, apps/studio/src/lib/projects/domains/index.ts, apps/studio/src/routes/editor/SettingsModal/Domain/Custom/Verification.tsx, apps/studio/src/routes/editor/SettingsModal/Domain/Custom/Verified.tsx, apps/studio/src/routes/editor/SettingsModal/Domain/index.tsx, apps/studio/src/routes/editor/SettingsModal/index.tsx, apps/studio/src/routes/editor/TopBar/Publish/Dropdown/Domain.tsx, apps/studio/src/routes/editor/TopBar/Publish/Dropdown/index.tsx, apps/studio/src/routes/editor/TopBar/Publish/TriggerButton.tsx
=> Hide custom domains

apps/studio/src/routes/editor/Canvas/Overlay/Chat.tsx
Closes: #1503
This PR addresses the issue where the "Chat with AI" button floats above the app bar. The changes ensure that the button is properly positioned below the app bar.
=> Fix: Correct positioning of "Chat with AI" button to prevent overlap with app bar

packages/ui/src/components/context-menu.tsx
This PR fixes an issue with the context menu behavior in the editor where users couldn't dismiss the menu by clicking within the canvas area. Previously, users had to click outside the entire canvas to dismiss the context menu, which created a poor user experience.
The fix modifies the ContextMenu component in the UI package to set `modal={false}` on the underlying Radix UI component. This change helps fixing the right-click bug.
Here's the [radix docs](https://www.radix-ui.com/primitives/docs/components/context-menu#root) source for modal
closes #1551 
No tests added
https://github.com/user-attachments/assets/77a42d3d-bc28-4530-8d66-ad023f6566be
=> fix: context-menu is closing after clicking outside the menu

apps/studio/electron/main/code/files.ts, apps/studio/src/components/Modals/Settings/Project/index.tsx, apps/studio/src/lib/editor/engine/canvas/index.ts, apps/studio/src/routes/editor/WebviewArea/Frame.tsx, apps/studio/src/routes/editor/WebviewArea/index.tsx
=> Update URL when changing project settings URL

apps/web/client/src/app/projects/import/local/_components/select-folder.tsx
There is a bug that prevents selecting directories when trying to upload a local project. 
I removed the accepts attributes as it accepts only files, and the webkitdirectory attribute allows only selecting directories, so this conflict ends up not being able to select anything. 
Before : 
https://github.com/user-attachments/assets/1ea56326-abbf-4a39-983b-1c4995f74e04
After : 
https://github.com/user-attachments/assets/c823d9f9-b150-4115-b9b3-a6783714a23a
=> Fix: Directory picker not working when uploading local projects

apps/web/client/src/components/store/editor/font/index.ts, packages/fonts/src/helpers/ast-generators.ts, packages/fonts/src/helpers/ast-manipulators.ts
Reverts onlook-dev/onlook#2867
=> Revert "fix: complete Google Font setup in brand panel"
